### ISSUE TITLE
😊

### ISSUE THREAD

**Issue by hx-code** [Kingbultsea/vue3-analysis#4]
#群主姐姐如何调试vue3 ssr啊
![微信图片_20211214151400](https://user-images.githubusercontent.com/71773836/145951073-7bf2128d-23a1-404e-b880-8e3148484e9e.png)
这两个属性是干嘛的

**Comment by yangliguo7** [comment]
ref ==> <div  ref="AAA“ >

**Comment by hx-code** [comment]
大佬强啊

**Comment by yangliguo7** [comment]
哈哈哈 不是 正好最近在看这个

**Comment by hx-code** [comment]
> ref ==> <div ref="AAA“ >



> 哈哈哈 不是 正好最近在看这个
快进群交流交流吧

**Comment by yangliguo7** [comment]
> > ref ==> <div ref="AAA“ >
> 
> > 哈哈哈 不是 正好最近在看这个
> > 快进群交流交流吧

什么群 ? 源码交流群 ?

**Comment by hx-code** [comment]
是啊发自我的手机
